# Site settings
title: Shaun Russell Full Stack Software Engineer and Entrepreneur
email: shaun.d.russell@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Shaun Russell considers himself a craftsman. His tools are Ruby, Javascript, Go, and open source databases.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://shaunrussell.com" # the base hostname & protocol for your site
twitter_username: shaunrussell
github_username:  shwing

# Build settings
markdown: kramdown
